// General APP Config
export const SET_OPEN_MODAL = 'SET_OPEN_MODAL';
export const SET_LOADING = 'SET_LOADING';

// Inventory
export const FETCH_INVENTORY_REQUESTED = 'FETCH_INVENTORY_REQUESTED';
export const FETCH_INVENTORY_REQUESTED_BY_ID =
  'FETCH_INVENTORY_REQUESTED_BY_ID';
export const FETCH_INVENTORY_FINISHED = 'FETCH_INVENTORY_FINISHED';
export const SET_INVENTORY_DETAILS = 'SET_INVENTORY_DETAILS';
export const SET_INVENTORY_ID = 'SET_INVENTORY_ID';
export const ADD_NEW_INVENTORY_REQUESTED = 'ADD_NEW_INVENTORY_REQUESTED';
export const UPDATE_INVENTORY_REQUESTED = 'UPDATE_INVENTORY_REQUESTED';
export const SET_TOTAL_DATA_INVENTORY = 'SET_TOTAL_DATA_INVENTORY';
export const SET_CURRENT_PAGE_INVENTORY = 'SET_CURRENT_PAGE_INVENTORY';
export const SET_SIZE_PER_PAGE_INVENTORY = 'SET_SIZE_PER_PAGE_INVENTORY';
export const SET_EDIT_INVENTORY = 'SET_EDIT_INVENTORY';

// Supplier
export const FETCH_SUPPLIER_REQUESTED = 'FETCH_SUPPLIER_REQUESTED';
export const FETCH_SUPPLIER_FINISHED = 'FETCH_SUPPLIER_FINISHED';
export const ADD_NEW_SUPPLIER_REQUESTED = 'ADD_NEW_SUPPLIER_REQUESTED';
export const UPDATE_SUPPLIER_REQUESTED = 'UPDATE_SUPPLIER_REQUESTED';
export const SET_SELECTED_DATA_SUPPLIER = 'SET_SELECTED_DATA_SUPPLIER';
export const SET_TOTAL_DATA_SUPPLIER = 'SET_TOTAL_DATA_SUPPLIER';
export const SET_CURRENT_PAGE_SUPPLIER = 'SET_CURRENT_PAGE_SUPPLIER';
export const SET_SIZE_PER_PAGE_SUPPLIER = 'SET_SIZE_PER_PAGE_SUPPLIER';
export const SET_EDIT_SUPPLIER = 'SET_EDIT_SUPPLIER';
